name: "🐛 Bug Report"
description: Let us know about a bug!
labels: bug
title: '[bug]'
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it?
      description: |
        Please be minimal and precise as possible. If your repo/run is public, please include a URL so it is easier for us to investigate.
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: checkboxes
    id: environment
    attributes:
      label: Which environments was this seen on?
      description: You may select more than one.
      options:
        - label: self-hosted
        - label: linux
        - label: window
        - label: macos
