blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation issues
    url: https://github.com/github/docs/issues
    about: Please file documentation issues in the github/docs repo.
  - name: 🙋 Ask a question
    url: https://github.community/
    about: Please ask and answer questions on GitHub Support Community.
  - name: 🔒 Report security vulnerability
    url: https://bounty.github.com/
    about: Please report security vulnerabilities to GitHub Security Bug Bounty.
