name: "🎁 Feature request"
description: Suggest a new feature/enhancement!
labels: enhancement
title: '[feat req]'
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
    validations:
      required: true

  - type: textarea
    id: reasoning
    attributes:
      label: Why is this needed?
    validations:
      required: true
